fix: remove mention of meeting frequency
solid/solid-oidc pull request #223
Opened 2023-09-12 15:35 UTC by woutermont

Action following multiple cases of uncertainty (cf. [matrix](https://matrix.to/#/!rUzJAFxzsTfTWEIQfp:gitter.im/$xEtmuBLbL7tVWIDI8gKVM1wh3u-LLlJIzLsJPOB674g?via=gitter.im&via=matrix.org&via=t2bot.io))

2023-09-13 12:13 UTC, elf-pavlik approved these changes

2023-09-17 22:28 UTC, csarven requested changes
Update along the lines of https://github.com/solid/authentication-panel/pull/238#pullrequestreview-1630134580

Or more specifically, remove all mentions/references to "panel". It is a repo of a work item.

2023-09-17 23:03 UTC, csarven approved these changes

2023-09-17 23:05 UTC, csarven commented
Decided to approve so to get something in quick/good enough.

2023-09-27 09:53 UTC, csarven commented on README.md
> +and associated communication channels are open to all
```suggestion
Anyone is welcome to join the Solid CG weekly or special topic meetings to discuss Solid OIDC. See [W3C calendar](https://www.w3.org/groups/cg/solid/calendar).

Chat in [Matrix](https://matrix.to/#/#solid_specification:gitter.im).
```

2023-09-27 09:53 UTC, merged